CREATE PROCEDURE [dbo].[spProductBin_Delete]
	@Id UNIQUEIDENTIFIER
AS
BEGIN TRAN DeleteProductBin
BEGIN TRY
	DELETE FROM ProductBin
	WHERE Id = @Id;
	COMMIT TRAN DeleteProductBin;
	RETURN @@ROWCOUNT;
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRAN DeleteProductBin
END CATCH