CREATE TABLE [dbo].[Charge]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(25) NOT NULL UNIQUE, -- TAX, DISCOUNT, SHIPPING AMOUNT
	[DateCreated] DATETIME NOT NULL,
	[CreatedByNodeId] DATETIME NOT NULL,
	[DateModified] DATETIME NULL,
	[ModifiedByNodeId] DATETIME NULL
	
)
