CREATE TABLE [dbo].[Charge]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(25) NOT NULL UNIQUE, -- TAX, DISCOUNT, SHIPPING AMOUNT
	[Description] VARCHAR(255) NULL,
	[DateCreated] DATETIME NOT NULL,
	[CreatedByNodeId] UNIQUEIDENTIFIER NOT NULL,
	[DateModified] DATETIME NULL,
	[ModifiedByNodeId] UNIQUEIDENTIFIER NULL
	
)
