CREATE TABLE [dbo].[Node]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL UNIQUE,
	[Description] VARCHAR(255) NULL,
	[DateCreated] DATETIME NOT NULL,
	[DateLastActive] DATETIME NULL
)
