CREATE TABLE [dbo].[OrderItem]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [OrderId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Order](Id) ON DELETE CASCADE, 
    [ProductId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].Product(Id), 
    [Quantity] INT NOT NULL DEFAULT 0, 
    [Amount] MONEY NOT NULL,
    UNIQUE([OrderId], [ProductId])
)
