CREATE TABLE [dbo].[OrderCharge]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [OrderId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.[Order](Id) ON DELETE CASCADE, 
    [ChargeId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Charge(Id) ON DELETE CASCADE, 
    [Amount] MONEY NOT NULL,
    UNIQUE([OrderId] ,[ChargeId])
)
