CREATE TABLE [dbo].[Order]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [MarketId] UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES dbo.Market(Id),
    [DateOrdered] DATETIME NOT NULL,
    [OrderNumber] VARCHAR(25) NOT NULL,
    [IsLocked] BIT NOT NULL DEFAULT 0,
    [LockedByTerminal] VARCHAR(50) NULL, 
    [BillAddressId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Address(Id), 
    [ShipAddressId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Address(Id), 
    [Status] NVARCHAR(50) NULL, 
    [IsPicked] BIT NOT NULL DEFAULT 0, 
    [DatePicked] DATETIME NULL, 
    [IsVerified] BIT NOT NULL DEFAULT 0, 
    [DateVerified] DATETIME NULL,
    [VerifiedByTerminal] VARCHAR(50) NULL, 
    [RequestedShipMethod] NVARCHAR(100) NULL, 
    [IsShipped] BIT NOT NULL DEFAULT 0, 
    [DateShipped] DATETIME NULL, 
    [ShipCost] MONEY NOT NULL, 
    [IsCancelled] BIT NOT NULL DEFAULT 0, 
    [DateCancelled] DATETIME NULL,
    [IsSkipped] BIT NOT NULL DEFAULT 0, 
    [DateSkipped] DATETIME NULL, 
    [Comments] NVARCHAR(MAX) NULL,                    
    [DateCreated] DATETIME NOT NULL, 
    [DateModified] DATETIME NULL,
    [RowVersion] BINARY(8) NULL,
    UNIQUE([ProviderId], [MarketId], [SalesNumber])
)
