CREATE TABLE [dbo].[ProductBin]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [ProductId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Product(Id) ON DELETE CASCADE, 
    [BinId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Bin(Id) ON DELETE CASCADE, 
    [Quantity] INT NOT NULL, 
    [DateCreated] DATETIME NOT NULL,
    [CreatedByNodeId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[Node](Id),
    [DateModified] DATETIME NULL,
    [ModifiedByNodeId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[Node](Id)
    UNIQUE([ProductId], [BinId])
)
