CREATE TABLE [dbo].[PurchaseOrder]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ExternalId] INT NULL,
	[PONumber] VARCHAR(15) UNIQUE NOT NULL,
	[SupplierId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Supplier]([Id]),
	[StatusId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [Status](Id),
	[Comments] NVARCHAR(MAX),
	[DateOrdered] DATE NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[DateModified] DATETIME NULL
)