CREATE TABLE [dbo].[State]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Code] VARCHAR(5) NOT NULL UNIQUE,
    [Name] NVARCHAR(100) NOT NULL UNIQUE, 
    [CountryId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.Country(Id)
)