INSERT INTO ProductBin
	(Id, ProductId, BinId, Quantity, DateCreated, CreatedByNodeId)
VALUES
	(NEWID(), (SELECT Id FROM Product WHERE SKU = '689228389267'), (SELECT Id FROM Bin WHERE Name = 'TestBin-B'), 1, GETDATE(), (SELECT Id FROM Node WHERE Name = 'IS-AUTH-01')),
	(NEWID(), (SELECT Id FROM Product WHERE SKU = '689228389267'), (SELECT Id FROM Bin WHERE Name = 'TestBin-M'), 2, GETDATE(), (SELECT Id FROM Node WHERE Name = 'IS-SERVER')),
	(NEWID(), (SELECT Id FROM Product WHERE SKU = '689228389267'), (SELECT Id FROM Bin WHERE Name = 'TestBin-T'), 3, GETDATE(), (SELECT Id FROM Node WHERE Name = 'IS-AUTH-01')),

	(NEWID(), (SELECT Id FROM Product WHERE SKU = '4710944224184'), (SELECT Id FROM Bin WHERE Name = 'TestBin-M'), 12, GETDATE(), (SELECT Id FROM Node WHERE Name = 'IS-AUTH-01')),
	(NEWID(), (SELECT Id FROM Product WHERE SKU = '689228561601'), (SELECT Id FROM Bin WHERE Name = 'TestBin-M'), 5, GETDATE(), (SELECT Id FROM Node WHERE Name = 'IS-AUTH-01')),
	(NEWID(), (SELECT Id FROM Product WHERE SKU = '643187000557'), (SELECT Id FROM Bin WHERE Name = 'TestBin-M'), 65, GETDATE(), (SELECT Id FROM Node WHERE Name = 'IS-SERVER')),

	(NEWID(), (SELECT Id FROM Product WHERE SKU = '047853625769'), (SELECT Id FROM Bin WHERE Name = 'TestBin-T'), 92, GETDATE(), (SELECT Id FROM Node WHERE Name = 'IS-SERVER'))