DECLARE @CountryId UNIQUEIDENTIFIER = (SELECT Id FROM Country WHERE Code = 'US');

INSERT INTO dbo.[State]
	(Id, Code, CountryId, Name)
VALUES
	(NEWID(),'AK',@CountryId,'Alaska'),
	(NEWID(),'AL',@CountryId,'Alabama'),
	(NEWID(),'AR',@CountryId,'Arkansas'),
	(NEWID(),'AS',@CountryId,'American Samoa'),
	(NEWID(),'AZ',@CountryId,'Arizona'),
	(NEWID(),'CA',@CountryId,'California'),
	(NEWID(),'CO',@CountryId,'Colorado'),
	(NEWID(),'CT',@CountryId,'Connecticut'),
	(NEWID(),'DC',@CountryId,'District of Columbia'),
	(NEWID(),'DE',@CountryId,'Delaware'),
	(NEWID(),'FL',@CountryId,'Florida'),
	(NEWID(),'FM',@CountryId,'Micronesia'),
	(NEWID(),'GA',@CountryId,'Georgia'),
	(NEWID(),'GU',@CountryId,'Guam'),
	(NEWID(),'HI',@CountryId,'Hawaii'),
	(NEWID(),'IA',@CountryId,'Iowa'),
	(NEWID(),'ID',@CountryId,'Idaho'),
	(NEWID(),'IL',@CountryId,'Illinois'),
	(NEWID(),'IN',@CountryId,'Indiana'),
	(NEWID(),'KS',@CountryId,'Kansas'),
	(NEWID(),'KY',@CountryId,'Kentucky'),
	(NEWID(),'LA',@CountryId,'Louisiana'),
	(NEWID(),'MA',@CountryId,'Massachusetts'),
	(NEWID(),'MD',@CountryId,'Maryland'),
	(NEWID(),'ME',@CountryId,'Maine'),
	(NEWID(),'MH',@CountryId,'Marshall Islands'),
	(NEWID(),'MI',@CountryId,'Michigan'),
	(NEWID(),'MN',@CountryId,'Minnesota'),
	(NEWID(),'MO',@CountryId,'Missouri'),
	(NEWID(),'MP',@CountryId,'Northern Marianas'),
	(NEWID(),'MS',@CountryId,'Mississippi'),
	(NEWID(),'MT',@CountryId,'Montana'),
	(NEWID(),'NC',@CountryId,'North Carolina'),
	(NEWID(),'ND',@CountryId,'North Dakota'),
	(NEWID(),'NE',@CountryId,'Nebraska'),
	(NEWID(),'NH',@CountryId,'New Hampshire'),
	(NEWID(),'NJ',@CountryId,'New Jersey'),
	(NEWID(),'NM',@CountryId,'New Mexico'),
	(NEWID(),'NV',@CountryId,'Nevada'),
	(NEWID(),'NY',@CountryId,'New York'),
	(NEWID(),'OH',@CountryId,'Ohio'),
	(NEWID(),'OK',@CountryId,'Oklahoma'),
	(NEWID(),'OR',@CountryId,'Oregon'),
	(NEWID(),'PA',@CountryId,'Pennsylvania'),
	(NEWID(),'PR',@CountryId,'Puerto Rico'),
	(NEWID(),'PW',@CountryId,'Palau'),
	(NEWID(),'RI',@CountryId,'Rhode Island'),
	(NEWID(),'SC',@CountryId,'South Carolina'),
	(NEWID(),'SD',@CountryId,'South Dakota'),
	(NEWID(),'TN',@CountryId,'Tennessee'),
	(NEWID(),'TX',@CountryId,'Texas'),
	(NEWID(),'UT',@CountryId,'Utah'),
	(NEWID(),'VA',@CountryId,'Virginia'),
	(NEWID(),'VI',@CountryId,'Virgin Islands'),
	(NEWID(),'VT',@CountryId,'Vermont'),
	(NEWID(),'WA',@CountryId,'Washington'),
	(NEWID(),'WI',@CountryId,'Wisconsin'),
	(NEWID(),'WV',@CountryId,'West Virginia'),
	(NEWID(),'WY',@CountryId,'Wyoming')